[theme]
name = "nord-dark"
[icons]
name = "material-nf"

[[block]]
block = "focused_window"
max_width = 50
show_marks = "visible"

[[block]]
block = "memory"
format_mem = "{mem_used}/{mem_total}({mem_used_percents})"
format_swap = "{swap_used}/{swap_total}({swap_used_percents})"
display_type = "memory"
icons = true
clickable = true
interval = 5
warning_mem = 80
warning_swap = 80
critical_mem = 95
critical_swap = 95

[[block]]
block = "cpu"
interval = 1
format = "{barchart} {utilization} {frequency}"

[[block]]
block = "net"
device = "wlp2s0"
format = "{ssid} {signal_strength} {speed_down;K*b} {graph_down;K*}"
interval = 1 

[[block]]
block = "battery"
interval = 10
format = "{percentage}"
device = "BAT0"

[[block]]
block = "sound"
format = "Vol {volume}"
on_click = "exec pavucontrol"

[[block]]
block = "keyboard_layout"
driver = "sway"
interval = 1

[[block]]
block = "backlight"
minimum = 0
maximum = 100
cycle = [100, 50, 0, 50]

[[block]]
block = "time"
format = "%m/%d %I:%M %P"
timezone = "Africa/Cairo"
interval = 60
locale = "en_US"
